version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./actual-data:/usr/src/app/actual-data
      - ./logs:/usr/src/app/logs
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
